### PR TITLE
Update react-native-navbar repo in package.json

### PR DESCRIPTION
**Pull request by osungjin**
malkomalko react-native-navbar ver is 1.1.7.
But this version has a bug in Android.
StatusBarIOS.setStyle work only IOS:
```
function customizeStatusBar(data) {
  if (Platform.OS === 'ios') {
    if (data.style) {
      StatusBarIOS.setStyle(data.style, true);
    }
    const animation = data.hidden ?
    (data.hideAnimation || NavigationBar.defaultProps.statusBar.hideAnimation) :
    (data.showAnimation || NavigationBar.defaultProps.statusBar.showAnimation);

    StatusBarIOS.setHidden(data.hidden, animation);
  }
}
```
So, You better to change react-navive-navbar repo or update malkomalko/react-native-navbar repo

### CODE REVIEW

**Comment by barock19** [comment]
+1

**Comment by wireblue** [comment]
+1

**Comment by ecasilla** [comment]
Can you update this PR to include the current semver for the react-native-navbar repo i think there at 1.5.0 please and thank you

**Comment by osungjin** [comment]
@ecasilla I changed. Check it plz.

**Pull request merged**
